name: ane-safari
region: nyc
services:
  - name: web
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${db.DATABASE_URL}
      - key: MODEL_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: MODEL_NAME
        scope: RUN_TIME
        value: o3-mini
      - key: WORKER_POLL_MS
        scope: RUN_TIME
        value: "60000"
databases:
  - name: db
    engine: PG
    version: "16"
    production: false
    cluster_name: ane-safari-db
